# Generated by Django 4.1.3 on 2022-11-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Комментарий')),
                ('author', models.CharField(default='Unknown', max_length=50, verbose_name='Автор')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.product', verbose_name='Статья')),
            ],
        ),
    ]
