# Generated by Django 4.1.4 on 2022-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
